export const AUTH_CONSTANTS = {
  CALLBACK_KEY: 'mc.state',
  SESSION_KEY: 'mc.session',
  LOCK_KEY: 'mc.lock',
  DEFAULT_TIMEOUT_SECONDS: 600,
  DEFAULT_RESPONSE_TYPE: 'code',
  DEFAULT_CLOCK_SKEW_SECONDS: 0,
  DEFAULT_CLOCK_TOLERANCE_SECONDS: 60,
  DEFAULT_VALIDATE_ID_TOKEN: true,
  DEFAULT_ID_TOKEN_SIGNING_ALG: 'RS256',
  DEFAULT_FEDERATED_SIGNOUT: true,
  DEFAULT_FETCH_USERINFO: true,
  DEFAULT_SCOPES: 'openid profile email',
  POPUP_WINDOW_WIDTH: 375,
  POPUP_WINDOW_HEIGHT: 600,
  FILTERED_ID_TOKEN_CLAIMS: [
    'iss',
    'exp',
    'nbf',
    'aud',
    'nonce',
    'iat',
    'auth_time',
    'c_hash',
    'at_hash',
    's_hash',
  ],
} as const;
